GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Vlad",
    "age":23
}

###
GET http://localhost:3000/books/

###
POST http://localhost:3000/books/
Content-Type: application/json

{
    "title":"4 fellows"
}

###

DELETE http://localhost:3000/users/62bf37a7186e23b974b8d7ae
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Alina222",
    "age": 20,
    "test":1
}

###

POST http://localhost:3000/users/62c195634428d427e641ff66/books HTTP/1.1
Content-Type: application/json

{
    "books":["62c05216f6d2a0d4b9a0f39e"]
}

###

GET http://localhost:3000/users/62bf36c5f18eabfd1c65bf7b/books HTTP/1.1