GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Alinet",
    "age":12
}

###
GET http://localhost:3000/books/

###
POST http://localhost:3000/books/
Content-Type: application/json

{
    "title":"4 fellows"
}

###

DELETE http://localhost:3000/users/62bf37a7186e23b974b8d7ae
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Alina",
    "age": 20,
}

//    "books": ["62c17d0cd3b8bb52cc5364f6", "62c05216f6d2a0d4b9a0f39e"]

###

POST http://localhost:3000/users/62c187b3ed85e5625eecd6af/books HTTP/1.1

Content-Type: application/json
{
    "books": ["62c183e427ab0264970bb1c9","62bf382b186e23b974b8d7bb"]
}

###
GET http://localhost:3000/users/62bf36c5f18eabfd1c65bf7b/books HTTP/1.1